#spring.application.name=demo

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5306/demo
    username: demo
    password: demo

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true    # sql ??
        show_sql: true      # sql ??
        highlight_sql: true # sql ??
#        dialect: MySQLDialect

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG